# Generated by Django 5.2.1 on 2025-06-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('enroll_course', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('UI/UX', 'UI/UX')], max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('education', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=30)),
                ('parent_name', models.CharField(max_length=30)),
                ('Dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('fees_paid', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('date_of_joining', models.DateField(blank=True, null=True, verbose_name='Joining Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/')),
            ],
        ),
    ]
