# Generated by Django 5.2.1 on 2025-06-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='subjec',
            new_name='subject',
        ),
    ]
