# Generated by Django 5.2.1 on 2025-06-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=30)),
                ('Experience', models.CharField(max_length=30)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('contact', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff/')),
            ],
        ),
    ]
